sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5tKLq2pp7t5EtizLvdu5
    access-key-secret: mhJ3r24STHH6TzdukwepWZKpsIDUHG
    bucket-name: sky-out-itcast-chanj
  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid: wxe2c5df8603117d02
    secret: 9cab1a62e721633986f2e83c2af900c7